### ISSUE TITLE
Add text procedures 

### ISSUE THREAD

**Issue by Willyboar** [Willyboar/rainbow#7]
Add text procedures (underline, bold, etc.)

**Comment by 0x4c756e61** [comment]
I could write those but the thing is, it's not well supported on terminal emulators and isn't at all on windows (at least CMD and powershell doesn't support any)

**Comment by 0x4c756e61** [comment]
I guess you can close that issue now

**Comment by Willyboar** [comment]
Yes. Thank you for the PR.

**Comment by 0x4c756e61** [comment]
> Yes. Thank you for the PR.

You are welcomed
